# Generated by Django 5.1.5 on 2025-01-27 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_teamjoinrequest'),
    ]

    operations = [
    ]
