# Generated by Django 5.1.5 on 2025-01-27 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20250127_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminvitation',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='team.team'),
            preserve_default=False,
        ),
    ]
