# Generated by Django 5.1.5 on 2025-01-26 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='parent_task',
        ),
    ]
